import { buildLayouts, layoutDescription } from './layouts.js';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const ASSET_BASE = new URL('.', import.meta.url);
const edition=document.body.dataset.edition||'original';
const graphStyle=getComputedStyle(document.body);
const palette={context:graphStyle.getPropertyValue('--graph-context').trim()||'#68e1c7',local:graphStyle.getPropertyValue('--graph-local').trim()||'#ffb178',global:graphStyle.getPropertyValue('--graph-global').trim()||'#83baff',unused:graphStyle.getPropertyValue('--graph-unused').trim()||'#57717d',edge:graphStyle.getPropertyValue('--graph-edge').trim()||'#59798555',label:graphStyle.getPropertyValue('--graph-label').trim()||'#c4d9de'};
const meta = {
  xela: {name:'Sparsh-skin', tag:'368 TAXELS · 3D GEOMETRY',description:'Magnetic skin · Allegro hand · 368 taxels',layout:'Measured taxel positions',metrics:['force','orientation','position','objects']},
  socks: {name:'Tactile Socks',tag:'453 TAXELS · PLANAR LAYOUT',description:'Piezoresistive fabric · 237 + 216 sensors',layout:'Physical sensor map · two disconnected feet',metrics:['actions','body']},
  deco: {name:'DECO-50',tag:'528 TRAINING NODES · PLANAR LAYOUT',description:'Piezoresistive skin · 2,124 raw taxels → 528 nodes',layout:'Canonical layout · two disconnected hands',metrics:['policy']}
};
const results={
 force:{title:'Force estimation',unit:'RMSE · cN · lower is better',decimals:2,rows:[['End-to-end',15,.92],['BYOL',23.79,.96],['MAE',21.55,2.06],['DINO',16.66,1.17],['Tactile-JEPA',14.05,.73]],headline:'6.3%',subtitle:'lower force error',copy:'14.05 cN, compared with 15.00 cN for the strongest baseline, end-to-end training.',note:'Reported mean ± spread. The 6.3% reduction compares aggregate RMSE with end-to-end training.'},
 orientation:{title:'In-hand orientation',unit:'RMSE · degrees · lower is better',decimals:2,rows:[['End-to-end',7.20,.87],['BYOL',6.92,.36],['MAE',8.38,.70],['DINO',8.27,.44],['Tactile-JEPA',5.48,.39]],headline:'20.8%',subtitle:'lower orientation error',copy:'5.48°, compared with 6.92° for BYOL, the strongest baseline on this metric.',note:'Reported mean ± spread. Orientation error is evaluated on the in-hand pose task.'},
 position:{title:'In-hand position',unit:'x accuracy · % · higher is better',decimals:2,rows:[['End-to-end',91.93,2.05],['BYOL',89.12,1.94],['MAE',85.13,4.15],['DINO',90.27,2.21],['Tactile-JEPA',95.74,1.05]],headline:'95.74%',subtitle:'position accuracy',copy:'Predictions within 2 cm of the ground truth along the x axis. End-to-end training reaches 91.93%.',note:'Accuracy at a 2 cm threshold along x. Bars start at zero; whiskers show the reported ± spread.',max:100},
 objects:{title:'Object classification',unit:'Top-1 accuracy · % · higher is better',decimals:2,rows:[['End-to-end',70.61,2.85],['BYOL',64.30,1.38],['MAE',63.44,.64],['DINO',83.26,.79],['Tactile-JEPA',83.27,3.36]],headline:'83.27%',subtitle:'object recognition',copy:'Across 14 objects. Performance is comparable to DINO (83.26%); the difference in means is negligible.',note:'Reported mean ± spread. A 0.01 percentage-point difference is not evidence of a meaningful improvement.',max:100},
 actions:{title:'Action classification',unit:'Top-1 accuracy · % · higher is better',decimals:2,rows:[['End-to-end',92.97,1.26],['BYOL',null],['MAE',null],['DINO',95.63,1.53],['Tactile-JEPA',96.91,1.92]],headline:'96.91%',subtitle:'activity recognition',copy:'Recognising nine activities from tactile socks. DINO reaches 95.63%; BYOL and MAE collapse in the reported setup.',note:'Reported mean ± spread. Collapsed runs have no numeric bar and are not treated as zero accuracy.',max:100},
 body:{title:'Full-body pose estimation',unit:'Mean joint RMSE · lower is better',decimals:2,rows:[['End-to-end',14.37,.30],['BYOL',null],['MAE',null],['DINO',13.78,.19],['Tactile-JEPA',13.42,.33]],headline:'13.42',subtitle:'reported joint RMSE',copy:'Predicting 19 relative joint angles from pressure histories. The strongest reported baseline, DINO, reaches 13.78.',note:'Values are transcribed from the draft. Its unit label is rad; the numeric scale should be verified before final publication.'},
 policy:{title:'Visuo-tactile policy learning',unit:'Action RMSE · normalized · lower is better',decimals:4,rows:[['Vision only',.5132,.0103],['Random features',.4969,.0118],['End-to-end',.4922,.0058],['BYOL',null],['MAE',.4400,.0021],['DINO',null],['Tactile-JEPA',.4634,.0029]],headline:'0.4634',subtitle:'action prediction error',copy:'Second-best in the supplied main table; MAE reaches 0.4400. Evaluation measures action prediction on Assembly demonstrations.',note:'Normalized-action RMSE over 16 future steps and 12 hand joints. This is offline prediction error, not a robot success rate.'}
};
const modeContent={mixed:['Local detail. <br>Global understanding.','Two compact regions and two scattered sets of sensors. The model learns to predict their representations from the visible context.'],local:['Learn the <br>local contact.','Four connected regions follow the sensor graph. Each hides a compact patch, encouraging prediction of local contact structure.'],global:['See the <br>whole surface.','Four sets of sensors are scattered across the sensing surface. Each target samples a broader view of the contact state.']};
let state={dataset:'xela',mode:'mixed',seed:0,context:'random',target:'all',edges:true,showTargets:true,showContext:true,layout:'spatial',raw:false,compare:false,yaw:-.20,pitch:.12,zoom:1,animation:1};
let data,points=[],layouts,cache={},loadId=0,animId,projected=[];
const canvas=$('#graph'),ctx=canvas.getContext('2d');
let width=700,height=450;
function resetCamera(){state.yaw=state.layout==='flat'?0:(state.dataset==='xela'?-.20:-.48);state.pitch=state.layout==='flat'?0:(state.dataset==='xela'?.12:-.36);state.zoom=1;draw()}
function updateLayoutInfo(){
 const info=layoutDescription(state.dataset,state.layout);
 $('#geometry-note').replaceChildren();
 const status=document.createElement('strong');status.textContent=info.status;
 $('#geometry-note').append(status,document.createTextNode(' '+info.detail));
 $('#layout-note').textContent=info.source;
 $('#geometry-tag').textContent=meta[state.dataset].tag.split(' · ')[0]+' · '+(state.layout==='flat'?'FLAT LAYOUT':'3D LAYOUT');
}
function setLayout(layout){
 if(!['flat','spatial'].includes(layout))return;
 state.layout=layout;$$('input[name="layout"]').forEach(input=>input.checked=input.value===layout);
 if(layouts)points=layouts[layout];
 $('#hover-info').hidden=true;updateLayoutInfo();resetCamera();
}
function currentSample(mode=state.mode){return data.masks[mode][state.seed]}
function updateMaskInfo(){if(!data)return;updateLegend();updateCustomize();const sample=currentSample(),context=sample.contexts[state.context],unique=new Set(sample.targets.flat());$('#mask-stats').innerHTML=`<div><strong>${context.visible.length}</strong><span>visible nodes</span></div><div><strong>${unique.size}</strong><span>target nodes · union</span></div>`;$('#context-note').textContent=state.context==='connected'?'Context grows locally within each sensing part. Removing targets may split it into disconnected pieces.':'Targets are removed from context. They may overlap one another.';if(state.raw&&state.showTargets)$('#context-note').textContent+=' Rings in the context colour mark raw-context nodes removed because they overlap targets.';$$('#target option').slice(1).forEach((o,i)=>o.textContent=`Target ${i+1} · ${sample.kinds[i]}${state.dataset!=='xela'?(i<2?' · left':' · right'):''}`)}
function stopAnimation(){cancelAnimationFrame(animId);state.animation=1;$('#animate').textContent='Play sampling';$('#animate').classList.remove('is-playing');if($('#sampling-status'))$('#sampling-status').textContent=state.showTargets?'Watch targets appear on the graph.':'Enable Targets to play the sampling animation.'}
function updateMode(mode){if(!modeContent[mode])return;state.mode=mode;stopAnimation();$$('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('#mode-title').innerHTML=edition==='original'?modeContent[mode][0]:({mixed:'Two local + two global targets',local:'Four local targets',global:'Four global targets'})[mode];$('#mode-copy').textContent=edition==='academic'?({mixed:'Two connected patches and two scattered sets of sensors.',local:'Four connected patches follow the sensor graph.',global:'Four sets of sensors sample the whole sensing surface.'})[mode]:modeContent[mode][1];updateMaskInfo();draw()}
async function setDataset(key){
 if(!meta[key])return;stopAnimation();state.dataset=key;state.seed=0;data=null;layouts=null;const request=++loadId;$('#load-status').hidden=false;$('#load-status').textContent='Loading sensor geometry…';$$('[data-dataset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.dataset===key)));const m=meta[key];$('#geometry-tag').textContent=m.tag;$('#dataset-description').textContent=m.description;updateLayoutInfo();$('#metric').innerHTML=m.metrics.map(k=>`<option value="${k}">${results[k].title}</option>`).join('');updateResults();draw();
 try{if(!cache[key]){const r=await fetch(new URL(`data/${key}.json`,ASSET_BASE));if(!r.ok)throw new Error('Data unavailable');cache[key]=await r.json()}if(request!==loadId)return;data=cache[key];layouts=buildLayouts(key,data);points=layouts[state.layout];$('#load-status').hidden=true;resetCamera();updateMaskInfo();resize()}catch(e){if(request===loadId){$('#load-status').textContent='The graph could not load. Select a dataset to try again.';console.error(e)}}
}
function project(p,x0,w,fit){const cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cx=Math.cos(state.pitch),sx=Math.sin(state.pitch);let x=p[0]*cy+p[2]*sy,z=-p[0]*sy+p[2]*cy,y=p[1]*cx-z*sx;z=p[1]*sx+z*cx;const scale=fit*state.zoom;return [x0+w/2+x*scale,height/2-y*scale,z]}
function drawView(mode,x0,w,record=true){
 if(edition==='academic')return drawAcademicView(mode,x0,w,record);
 const sample=currentSample(mode),contexts=sample.contexts[state.context];const raw=new Set(contexts.raw),visible=new Set(state.raw?contexts.raw:contexts.visible);const local=new Set(),global=new Set(),union=new Set(sample.targets.flat());sample.targets.forEach((t,i)=>{if(!state.showTargets)return;if(state.target!=='all'&&Number(state.target)!==i)return;const take=t.slice(0,Math.ceil(t.length*state.animation));take.forEach(n=>(sample.kinds[i]==='local'?local:global).add(n))});
 const spans=[0,1].map(d=>Math.max(...points.map(p=>p[d]))-Math.min(...points.map(p=>p[d])));const fit=Math.min(w*.80/spans[0],height*.78/spans[1]);
 const ps=points.map(p=>project(p,x0,w,fit));if(record)projected.push(...ps.map((p,i)=>({p,id:i,mode})));
 ctx.save();ctx.beginPath();ctx.rect(x0,0,w,height);ctx.clip();
 if(state.edges){ctx.lineWidth=.7;ctx.strokeStyle=palette.edge;ctx.beginPath();data.edges.forEach(([a,b])=>{ctx.moveTo(ps[a][0],ps[a][1]);ctx.lineTo(ps[b][0],ps[b][1])});ctx.stroke();ctx.lineWidth=1.35;ctx.strokeStyle=palette.local+'80';ctx.beginPath();data.edges.forEach(([a,b])=>{if(local.has(a)&&local.has(b)){ctx.moveTo(ps[a][0],ps[a][1]);ctx.lineTo(ps[b][0],ps[b][1])}});ctx.stroke()}
 const order=ps.map((p,i)=>i).sort((a,b)=>ps[a][2]-ps[b][2]);const radius=Math.max(1.4,Math.min(3.4,w/210))*Math.sqrt(state.zoom);
 for(const i of order){let colour=palette.unused,r=radius*.70;const isLocal=local.has(i),isGlobal=global.has(i);if(state.showContext&&visible.has(i)){colour=palette.context;r=radius}if(isGlobal){colour=palette.global;r=radius*1.18}if(isLocal){colour=palette.local;r=radius*1.22}const [x,y]=ps[i];ctx.beginPath();ctx.fillStyle=colour;ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(isGlobal&&isLocal){ctx.strokeStyle=palette.global;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r+2,0,Math.PI*2);ctx.stroke()}if(state.showTargets&&state.raw&&state.showContext&&raw.has(i)&&union.has(i)){ctx.strokeStyle=palette.context;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,r+3,0,Math.PI*2);ctx.stroke()}}
 if(state.compare){ctx.font='12px "DM Sans", sans-serif';ctx.textAlign='center';ctx.fillStyle=palette.label;ctx.fillText(mode==='mixed'?'Mixed · 2L + 2G':mode==='global'?'Global · 4G':'Local · 4L',x0+w/2,24)}ctx.restore();
}
function draw(){if(!ctx)return;ctx.clearRect(0,0,width,height);projected=[];if(!data)return;if(state.compare){drawView(state.mode,0,width/2);drawView(state.mode==='local'?'mixed':'local',width/2,width/2);ctx.beginPath();ctx.strokeStyle=palette.edge;ctx.moveTo(width/2,18);ctx.lineTo(width/2,height-18);ctx.stroke()}else drawView(state.mode,0,width)}
function resize(){const box=canvas.getBoundingClientRect();width=box.width;height=box.height;const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function updateResults(){const key=$('#metric').value,r=results[key];if(!r)return;$('#chart-title').textContent=r.title;$('#chart-unit').textContent=r.unit;$('#result-dataset').textContent=edition==='academic'?meta[state.dataset].name:meta[state.dataset].name.toUpperCase();$('#result-headline').textContent=r.headline;$('#result-subtitle').textContent=r.subtitle;$('#result-copy').textContent=r.copy;$('#metric-note').textContent=r.note;const max=r.max||Math.max(...r.rows.filter(v=>v[1]!=null).map(v=>v[1]+v[2]))*1.07;$('#chart').innerHTML=r.rows.map(([label,value,spread])=>{const ours=label==='Tactile-JEPA';return `<div class="bar-row ${ours?'ours':''} ${value==null?'collapsed':''}"><span>${label}</span><div class="bar-track" aria-hidden="true">${value==null?'':`<div class="bar" style="width:${value/max*100}%"></div><div class="bar-whisker" style="left:${(value-spread)/max*100}%;width:${spread*2/max*100}%"></div>`}</div><span class="bar-value">${value==null?'Collapsed':`${value.toFixed(r.decimals)} ± ${spread.toFixed(r.decimals)}`}</span></div>`}).join('')}
$$('input[name="layout"]').forEach(input=>input.addEventListener('change',()=>setLayout(input.value)));
$$('[data-dataset]').forEach(b=>b.addEventListener('click',()=>setDataset(b.dataset.dataset)));
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>updateMode(b.dataset.mode)));
$('#resample').onclick=()=>{if(!data)return;state.seed=(state.seed+1)%8;stopAnimation();updateMaskInfo();draw()};
$('#animate').onclick=()=>{if(!data||!state.showTargets)return;if(state.animation<1){stopAnimation();draw();return}if(edition==='academic'&&matchMedia('(max-width: 850px)').matches&&canvas.getBoundingClientRect().bottom>innerHeight)canvas.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});const start=performance.now(),duration=matchMedia('(prefers-reduced-motion: reduce)').matches?300:3600;state.animation=0;$('#animate').textContent='Stop sampling';$('#animate').classList.add('is-playing');if($('#sampling-status'))$('#sampling-status').textContent='Sampling targets…';function tick(now){state.animation=Math.min(1,(now-start)/duration);draw();if(state.animation<1)animId=requestAnimationFrame(tick);else{$('#animate').textContent='Replay sampling';$('#animate').classList.remove('is-playing');if($('#sampling-status'))$('#sampling-status').textContent='Sampling complete. Try a new sample or strategy.'}}animId=requestAnimationFrame(tick)};
$('#context').onchange=e=>{state.context=e.target.value;updateMaskInfo();draw()};$('#target').onchange=e=>{state.target=e.target.value;updateLegend();updateCustomize();draw()};
for(const [id,key] of [['show-targets','showTargets'],['edges','edges'],['show-context','showContext'],['raw-context','raw'],['compare','compare']])$('#'+id).onchange=e=>{state[key]=e.target.checked;if(key==='showTargets'){stopAnimation();$('#animate').disabled=!state.showTargets;$('#target').disabled=!state.showTargets;document.body.classList.toggle('targets-hidden',!state.showTargets)}updateMaskInfo();draw()};
$('#reset-view').onclick=resetCamera;$('#front-view').onclick=()=>{state.yaw=0;state.pitch=0;state.zoom=1;draw()};$('#metric').onchange=updateResults;
let drag=null,moved=false;
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,id:e.pointerId};moved=false;canvas.setPointerCapture(e.pointerId);$('#hover-info').hidden=true});
canvas.addEventListener('pointermove',e=>{if(drag){state.yaw+=(e.clientX-drag.x)*.008;state.pitch=Math.max(-1.45,Math.min(1.45,state.pitch+(e.clientY-drag.y)*.008));moved=true;drag.x=e.clientX;drag.y=e.clientY;draw();return}const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;let closest=null,dist=100;for(const p of projected){const d=(p.p[0]-x)**2+(p.p[1]-y)**2;if(d<dist){closest=p;dist=d}}const tip=$('#hover-info');if(!closest||!data){tip.hidden=true;return}const i=closest.id,s=currentSample(closest.mode);const ts=s.targets.map((t,j)=>t.includes(i)?`T${j+1}`:null).filter(Boolean).join(', ');tip.textContent=`Node ${i} · ${data.labels[i]} · ${ts|| (s.contexts[state.context].visible.includes(i)?'visible context':'unselected')}`;tip.hidden=false;tip.style.left=Math.max(10,Math.min(width-235,x+12))+'px';tip.style.top=(rect.top-$('#viewport').getBoundingClientRect().top+y+14)+'px'});
function endDrag(){drag=null}canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);canvas.addEventListener('pointerleave',()=>{$('#hover-info').hidden=true});canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.55,Math.min(2.8,state.zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});
canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key))return;e.preventDefault();if(e.key==='Home')return resetCamera();if(e.key==='ArrowLeft')state.yaw-=.12;if(e.key==='ArrowRight')state.yaw+=.12;if(e.key==='ArrowUp')state.pitch=Math.max(-1.45,state.pitch-.12);if(e.key==='ArrowDown')state.pitch=Math.min(1.45,state.pitch+.12);if(e.key==='+'||e.key==='=')state.zoom=Math.min(2.8,state.zoom*1.1);if(e.key==='-')state.zoom=Math.max(.55,state.zoom/1.1);draw()});
const targetColours=edition==='academic'?['#974c3e','#426779','#80613d','#536b4a']:['#c15a13','#285fc7','#af3683','#008478'];
function updateCustomize(){const badge=$('#customize-state');if(!badge)return;const n=Number(state.context!=='random')+Number(state.target!=='all')+Number(!state.edges)+Number(state.raw)+Number(state.compare);badge.textContent=n?`${n} changed`:'optional'}
function updateLegend(){const legend=$('#target-legend');if(!legend||!data)return;const sample=currentSample();legend.innerHTML=sample.kinds.map((kind,i)=>`<span class="target-key ${!state.showTargets||(state.target!=='all'&&Number(state.target)!==i)?'dimmed':''}" data-target-legend><i class="shape ${kind}" style="--target-color:${targetColours[i]}" aria-hidden="true"></i>T${i+1} · ${kind}</span>`).join('')+'<span class="context-key"><i class="dot" aria-hidden="true"></i>Context</span><span class="unselected-key"><i class="dot" aria-hidden="true"></i>Unselected</span>'}
function drawAcademicView(mode,x0,w,record){
 const sample=currentSample(mode),context=sample.contexts[state.context];
 const visible=new Set(state.raw?context.raw:context.visible),raw=new Set(context.raw),union=new Set(sample.targets.flat());
 const memberships=Array.from({length:points.length},()=>[]);
 sample.targets.forEach((target,t)=>{if(!state.showTargets||(state.target!=='all'&&Number(state.target)!==t))return;const progress=state.target==='all'?Math.max(0,Math.min(1,state.animation*4-t)):state.animation;target.slice(0,Math.ceil(target.length*progress)).forEach(i=>memberships[i].push(t))});
 const spans=[0,1].map(d=>Math.max(...points.map(p=>p[d]))-Math.min(...points.map(p=>p[d]))),fit=Math.min(w*.80/spans[0],height*.78/spans[1]);
 const ps=points.map(p=>project(p,x0,w,fit));if(record)projected.push(...ps.map((p,i)=>({p,id:i,mode})));
 ctx.save();ctx.beginPath();ctx.rect(x0,0,w,height);ctx.clip();
 if(state.edges){ctx.lineWidth=.65;ctx.strokeStyle='#aab0b455';ctx.beginPath();data.edges.forEach(([a,b])=>{ctx.moveTo(ps[a][0],ps[a][1]);ctx.lineTo(ps[b][0],ps[b][1])});ctx.stroke();for(let t=0;t<4;t++){if(sample.kinds[t]!=='local')continue;ctx.lineWidth=.85;ctx.strokeStyle=targetColours[t]+'75';ctx.beginPath();data.edges.forEach(([a,b])=>{if(memberships[a].includes(t)&&memberships[b].includes(t)){ctx.moveTo(ps[a][0],ps[a][1]);ctx.lineTo(ps[b][0],ps[b][1])}});ctx.stroke()}}
 const radius=Math.max(1.25,Math.min(3.1,w/230))*Math.sqrt(state.zoom),order=ps.map((_,i)=>i).sort((a,b)=>ps[a][2]-ps[b][2]);
 function shape(x,y,r,kind){ctx.beginPath();if(kind==='global'){ctx.moveTo(x,y-r*1.2);ctx.lineTo(x+r*1.2,y);ctx.lineTo(x,y+r*1.2);ctx.lineTo(x-r*1.2,y);ctx.closePath()}else ctx.arc(x,y,r,0,Math.PI*2)}
 for(const i of order){const [x,y]=ps[i],targets=memberships[i];let r=radius*.64;ctx.fillStyle=state.showContext&&visible.has(i)?'#a0a6aa':'#dedfdf';if(state.showContext&&visible.has(i))r=radius*.82;shape(x,y,r,'local');ctx.fill();if(targets.length){const t=targets[0];r=radius*1.13;shape(x,y,r,sample.kinds[t]);ctx.fillStyle=targetColours[t];ctx.fill();ctx.strokeStyle='#ffffff';ctx.lineWidth=.65;ctx.stroke();if(targets.length>1){const step=2*Math.PI/targets.length;targets.forEach((j,k)=>{ctx.beginPath();ctx.arc(x,y,r+1.7,k*step+.10,(k+1)*step-.10);ctx.strokeStyle=targetColours[j];ctx.lineWidth=1.5;ctx.stroke()})}}if(state.showTargets&&state.showContext&&state.raw&&raw.has(i)&&union.has(i)){ctx.beginPath();ctx.arc(x,y,r+3.4,0,Math.PI*2);ctx.strokeStyle='#637589';ctx.lineWidth=1;ctx.setLineDash([2,2]);ctx.stroke();ctx.setLineDash([])}}
 if(state.compare){ctx.fillStyle='#53657a';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(mode==='mixed'?'Mixed · 2L + 2G':mode==='local'?'Local · 4L':'Global · 4G',x0+w/2,17)}ctx.restore();
}

new ResizeObserver(resize).observe(canvas);
const samplingDialog=$('#sampling-dialog');if(samplingDialog){$('#customize').onclick=()=>samplingDialog.showModal();samplingDialog.addEventListener('click',e=>{if(e.target===samplingDialog){const r=samplingDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)samplingDialog.close()}})}
updateMode('mixed');setDataset('xela');

// Native dialog preserves keyboard focus, Escape dismissal and screen-reader semantics.
const figureDialog=$('#figure-dialog'),figureScroll=$('.figure-scroll');
const figures={teaser:{title:'From tactile signals to representations',src:'images/teaser.png',pdf:'images/teaser11.pdf'},pretrain:{title:'Pre-training and downstream applications',src:'images/pretrain.png',pdf:'images/pretrain2.pdf'}};
function setFigureZoom(zoomed){figureScroll.classList.toggle('zoomed',zoomed);$('#figure-zoom').textContent=zoomed?'Fit image':'Zoom in'}
$$('[data-figure]').forEach(button=>button.addEventListener('click',()=>{const f=figures[button.dataset.figure];$('#figure-title').textContent=f.title;$('#figure-full').src=new URL(f.src,ASSET_BASE).href;$('#figure-full').alt=button.querySelector('img').alt;$('#figure-pdf').href=new URL(f.pdf,ASSET_BASE).href;setFigureZoom(false);figureDialog.showModal();figureScroll.scrollTop=0;figureScroll.scrollLeft=0}));
$('#figure-close').onclick=()=>figureDialog.close();$('#figure-zoom').onclick=()=>setFigureZoom(!figureScroll.classList.contains('zoomed'));figureDialog.addEventListener('click',e=>{if(e.target===figureDialog){const r=figureDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)figureDialog.close()}});
